### PR TITLE
Compliance Reporting

### PR DESCRIPTION
**Pull request by amichard**
#1071 #1075 #1091 #1092 

This should wire up the remaining tables: Energy Density, Energy Effectiveness Ratio and Default Carbon Intensity

Changelog:
- Added migration for additional fuel types
- Increased length of Approved Fuel name
- Added fixture for Energy Density
- Added fixture for Energy Effectiveness
- Added fixture for Default Carbon Intensity
- Layout improvements

/ignore-bot-length

### CODE REVIEW

**Comment by amichard** [comment]
[Credit Calculation | View CI Limits |5| v1.3.3](https://trello.com/c/mfCiH2IR/888-credit-calculation-view-ci-limits-5-v133)

**Comment by amichard** [comment]
[Credit Calculation | View Energy Effectiveness Ratio EER values |5| v1.3.3](https://trello.com/c/UlZX9VeP/890-credit-calculation-view-energy-effectiveness-ratio-eer-values-5-v133)

**Comment by amichard** [comment]
[Credit Calculation | View Energy Densities |5| v1.3.3](https://trello.com/c/oViXS5Ty/893-credit-calculation-view-energy-densities-5)

**Comment by amichard** [comment]
[Credit Calculation | View Default Carbon Intensities |5| v1.3.3](https://trello.com/c/FCwfPTOt/895-credit-calculation-view-default-carbon-intensities-5)

**Comment by kuanfandevops** [comment]
@amichard there are some conflicts need to resolve.
Also do the scripts under operational folder need to run manually for each env or they will be automatically loaded.

**Comment by amichard** [comment]
they have to be manually loaded @kuanfandevops 

```
python manage.py load_ops_data api/fixtures/operational/0005_add_new_compliance_periods.py
```

```
python manage.py load_ops_data api/fixtures/operational/0006_add_carbon_intensity_limits.py
```

```
python manage.py load_ops_data api/fixtures/operational/0007_add_energy_effectiveness_ratios.py
```

```
python manage.py load_ops_data api/fixtures/operational/0008_add_default_carbon_intensities.py
```

```
python manage.py load_ops_data api/fixtures/operational/0009_add_energy_densities.py
```

**Pull request merged**
