### PR TITLE
Modal submission

### PR DESCRIPTION
**Pull request by amichard**
#265 #274 #279 #280 #282 #283 

Added a modal confirmation before letting the user propose (Sign) a credit transfer.
... And at a bunch of minor fixes.

Changelog:
- Created Checkbox Component
- Sign 1/2 requires the terms to be checked before it's enabled
- Modal Confirmation when Signing a credit transfer
- Refactored the error screens to make it more compliant to linting
- Changed 500 and 502 error message to use "is experiencing some technical difficulties."
- Changed Visual Representation so that the icons are no longer angled
- Fixed Unit Tests

### CODE REVIEW

**Comment by amichard** [comment]
[Confirmation Alerts | Send (Sign 1/2) a Credit Transfer Proposal |1|](https://trello.com/c/wbd97Fj6/381-confirmation-alerts-send-sign-1-2-a-credit-transfer-proposal-1)

**Comment by amichard** [comment]
[Signing Authority | Confirm Regulation Statements when sending a Credit Transfer Proposal to another fuel supplier |1|](https://trello.com/c/5i5DG7jE/511-signing-authority-confirm-regulation-statements-when-sending-a-credit-transfer-proposal-to-another-fuel-supplier-1)

**Comment by amichard** [comment]
[Front End | Unit Testing |3|](https://trello.com/c/aMeS3ZEf/604-front-end-unit-testing-3)

**Comment by amichard** [comment]
[Authentication | Show proper error message when not authenticated (API is down) |1| [permissions] [v0.2.0]](https://trello.com/c/3qmIlIxE/365-authentication-show-proper-error-message-when-not-authenticated-api-is-down-1-permissions-v020)

**Comment by amichard** [comment]
[UX Refactor | Rethinking the graphic on the Credit Transaction View screen |3| [v0.2.0]](https://trello.com/c/qaUd7URs/585-ux-refactor-rethinking-the-graphic-on-the-credit-transaction-view-screen-3-v020)

**Comment by amichard** [comment]
[Filtering | Fix issues with the search / filter function in the Credit Transactions Table - Part 2 |1| [v0.2.0]](https://trello.com/c/tINnVbon/603-filtering-fix-issues-with-the-search-filter-function-in-the-credit-transactions-table-part-2-estimate-v020)

**Comment by kuanfandevops** [comment]
Sybrand reviewed and approved this PR

**Pull request merged**
