### PR TITLE
Rename Approved to Record and Completed to Approved

### PR DESCRIPTION
**Pull request by amichard**
#675 #676

Changed some of the credit trade status labels

Changelog:
- Added migration
  - Changed Approved to Recorded
  - Changed Completed to Approved
- When approving a credit transfer, the system no longer creates an approved history
- Updated tests
- Changed the colours to follow the government specs: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/web-content-development-guides/developers-guide/css-elements#colours

### CODE REVIEW

**Comment by plasticviking** [comment]
It looks like there are three frontend (jest) test failures due to the new statuses.

**Comment by amichard** [comment]
Good catch. Fixed the tests. I got rid of the checkbox test. Not sure why it was reporting null. I decided to just get rid of it since Nick is working on better tests anyway

**Comment by amichard** [comment]
[Roles | Create Deputy Director Role IDIR |1|](https://trello.com/c/7165Swbm/912-roles-create-deputy-director-role-idir-1)

**Comment by amichard** [comment]
[Credit Transactions | Adjust the Approval Transaction History entry when using the Historical Data Entry |5| v1.1.1](https://trello.com/c/AY2F5AK0/880-credit-transactions-adjust-the-approval-transaction-history-entry-when-using-the-historical-data-entry-5)

**Comment by amichard** [comment]
[Credit Transactions | Add an Analyst Transaction History entry when using the Historical Data Entry feature |5| v1.1.1](https://trello.com/c/DWfW6xoZ/911-credit-transactions-add-an-analyst-transaction-history-entry-when-using-the-historical-data-entry-feature-5)

**Pull request merged**
